### ISSUE TITLE
Responsive checklist

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#476]
Aici vom pune toate lucrurile rămase de făcut. Pentru cele mari putem deschide issues.

### Pre-release

- [x] #470 unde punem linkul „personalizare elemente” și cum aliniem casetele când unele sunt ascunse?
- [x] ce cutii sociale afișăm pe prima pagină?
- [x] este ok să nu mai afișăm butonul de FB pe navbar?
- [x] de regenerat bootstrap.min.css cu noua culoare pentru info
- [x] opțiunile de căutare full-text sau într-o sursă anume au dispărut; le-aș pune la loc, urmând să rezolvăm problema separat, nu în acest branch;
- [x] grep după `skin` - ar trebui să dispară cu totul;
- [x] tot ce ține de posibilitatea de a alege skinul trebuie să dispară - preferințe, câmp pe `User` în baza de date etc.;
- [x] comentariile la definiții ([exemplu](https://dexonline.ro/definitie/surjectiv)) trebuie convertite;
- [x] grep după `paragraphTitle` - trebuie minim convertite la `<h3>`, dar pot fi indicii că întreaga pagină nu a fost convertită la Bootstrap;

### Post-release
- [x] sincronizează `dex.conf` și `nginx.conf` cu fișierele sample;
- [x] șterge din Varnish codul care detectează dispozitivele mobile și codul care hash-uiește skin-ul;
- [x] șterge câmpul `User.skin` din baza de date; aplică patchul și la bazele de date LOC_*;
- [x] fă testele să meargă din nou;
- [ ] înlocuiește icoanele rămase în `www/img/icons` cu glyphicons sau altceva;
- [x] descarcă toate articolele (`php tools/syncWikiArticles.php --force`);
- [x] postare pe blog;

**Comment by sandriu** [comment]
Pentru lista de pre-release, am bifat eu:
- punctul 1 (#470);
- punctele 2 și 3, discutate cu Radu și David la bere, pe 6 august;
- punctul 4 (#477).

Ce aș mai face la pre-release:
- [ ] înlocuit box-shadow-ul roșu de pe cutia de căutare.

**Comment by aifrim** [comment]
Eram pe pagina de licență și am descoperit asta:

![image](https://cloud.githubusercontent.com/assets/825952/17856025/3ba52ae8-6884-11e6-96e4-e6bf2d634b17.png)

Se poate ascunde ceea ce e în plus pe widget-ul acela de Facebook Like printr-un `overflow-x: hidden` pus pe `.fbBottom`

**Comment by CatalinFrancu** [comment]
@aifrim Mulțumesc! Și pe mine mă enerva.

**Comment by aifrim** [comment]
@CatalinFrancu 

Cu plăcere!
